name: Generate Snake Animation

on:
	schedule: [{cron: "0 0 * * *"}]
	
	# allows to manually run the job at any time
	workflow_dispatch:
	
	# run on every push on the master branch
	push:
		branches:
		- main
		
jobs:
	generate:
		runs-on: ubuntu-latest
		
		steps:
			-	name: Most used langs
				uses: lowlighter/metrics@latest
				with:
					filename: metrics.plugin.languages.svg
					token: ${{ secrets.METRICS_TOKEN }}
					base: ""
					plugin_languages: yes
					plugin_languages_details: bytes-size, percentage

			-	name: Indepth contributions analysis
				uses: lowlighter/metrics@latest
				with:
					filename: metrics.plugin.notable.indepth.svg
					token: ${{ secrets.METRICS_TOKEN }}
					base: ""
					plugin_notable: yes
					plugin_notable_indepth: yes
					plugin_notable_repositories: yes